/**
 * Hardcoded services data for Fonsi by Cristal
 * Matches the website services - used for offline/fallback
 */

import { Service } from '@types/index';

export const SERVICES: Service[] = [
  // Hair Services (18 services)
  {
    id: 'hair-1',
    name: 'Blowout',
    category: 'Hair',
    description: 'Professional blow dry styling',
    priceMin: 35,
    priceMax: 50,
    duration: 45,
  },
  {
    id: 'hair-2',
    name: 'Bridal Blowout',
    category: 'Hair',
    description: 'Bridal styling and blow dry',
    priceMin: 60,
    priceMax: 85,
    duration: 60,
  },
  {
    id: 'hair-3',
    name: 'Hair Cut',
    category: 'Hair',
    description: 'Professional haircut with styling',
    priceMin: 45,
    priceMax: 70,
    duration: 45,
  },
  {
    id: 'hair-4',
    name: 'Hair Cut & Color',
    category: 'Hair',
    description: 'Haircut with full color service',
    priceMin: 90,
    priceMax: 150,
    duration: 120,
  },
  {
    id: 'hair-5',
    name: 'Hair Color - Root Touch Up',
    category: 'Hair',
    description: 'Root touch up color service',
    priceMin: 50,
    priceMax: 80,
    duration: 75,
  },
  {
    id: 'hair-6',
    name: 'Hair Color - Full Head',
    category: 'Hair',
    description: 'Full head color service',
    priceMin: 80,
    priceMax: 130,
    duration: 120,
  },
  {
    id: 'hair-7',
    name: 'Hair Color - Highlights',
    category: 'Hair',
    description: 'Highlights or balayage service',
    priceMin: 100,
    priceMax: 200,
    duration: 150,
  },
  {
    id: 'hair-8',
    name: 'Hair Treatment',
    category: 'Hair',
    description: 'Deep conditioning or keratin treatment',
    priceMin: 40,
    priceMax: 75,
    duration: 60,
  },
  {
    id: 'hair-9',
    name: 'Hair Extensions',
    category: 'Hair',
    description: 'Hair extension application and styling',
    priceMin: 150,
    priceMax: 300,
    duration: 180,
  },
  {
    id: 'hair-10',
    name: 'Ombré/Balayage',
    category: 'Hair',
    description: 'Ombré or balayage color service',
    priceMin: 120,
    priceMax: 220,
    duration: 150,
  },
  {
    id: 'hair-11',
    name: 'Perm',
    category: 'Hair',
    description: 'Hair perm service',
    priceMin: 80,
    priceMax: 130,
    duration: 120,
  },
  {
    id: 'hair-12',
    name: 'Hair Wash & Style',
    category: 'Hair',
    description: 'Professional wash and styling',
    priceMin: 25,
    priceMax: 40,
    duration: 30,
  },
  {
    id: 'hair-13',
    name: 'Updo',
    category: 'Hair',
    description: 'Updo hairstyle for special occasions',
    priceMin: 50,
    priceMax: 85,
    duration: 60,
  },
  {
    id: 'hair-14',
    name: 'Braids',
    category: 'Hair',
    description: 'Professional braiding service',
    priceMin: 45,
    priceMax: 100,
    duration: 90,
  },
  {
    id: 'hair-15',
    name: 'Relaxer',
    category: 'Hair',
    description: 'Hair relaxer service',
    priceMin: 60,
    priceMax: 100,
    duration: 90,
  },
  {
    id: 'hair-16',
    name: 'Trim',
    category: 'Hair',
    description: 'Quick hair trim',
    priceMin: 20,
    priceMax: 35,
    duration: 20,
  },
  {
    id: 'hair-17',
    name: 'Consultation',
    category: 'Hair',
    description: 'Hair consultation with stylist',
    priceMin: 0,
    priceMax: 25,
    duration: 30,
  },
  {
    id: 'hair-18',
    name: 'Special Event Hair',
    category: 'Hair',
    description: 'Special occasion hairstyling',
    priceMin: 75,
    priceMax: 150,
    duration: 90,
  },

  // Bridal Services (3 services)
  {
    id: 'bridal-1',
    name: 'Bridal Hair & Makeup',
    category: 'Bridal',
    description: 'Complete bridal hair and makeup package',
    priceMin: 150,
    priceMax: 250,
    duration: 120,
  },
  {
    id: 'bridal-2',
    name: 'Bridal Hair Only',
    category: 'Bridal',
    description: 'Bridal hair styling service',
    priceMin: 80,
    priceMax: 130,
    duration: 75,
  },
  {
    id: 'bridal-3',
    name: 'Bridal Trial',
    category: 'Bridal',
    description: 'Trial hair and makeup session before wedding',
    priceMin: 100,
    priceMax: 150,
    duration: 90,
  },

  // Makeup Services (3 services)
  {
    id: 'makeup-1',
    name: 'Makeup Application',
    category: 'Makeup',
    description: 'Professional makeup application',
    priceMin: 45,
    priceMax: 75,
    duration: 45,
  },
  {
    id: 'makeup-2',
    name: 'Eye Makeup',
    category: 'Makeup',
    description: 'Eye makeup styling and application',
    priceMin: 20,
    priceMax: 40,
    duration: 30,
  },
  {
    id: 'makeup-3',
    name: 'Special Event Makeup',
    category: 'Makeup',
    description: 'Special occasion makeup service',
    priceMin: 60,
    priceMax: 100,
    duration: 60,
  },

  // Waxing Services (1 service)
  {
    id: 'waxing-1',
    name: 'Waxing',
    category: 'Waxing',
    description: 'Professional waxing service',
    priceMin: 15,
    priceMax: 75,
    duration: 30,
  },
];

// Group services by category
export const SERVICES_BY_CATEGORY = {
  Hair: SERVICES.filter((s) => s.category === 'Hair'),
  Bridal: SERVICES.filter((s) => s.category === 'Bridal'),
  Makeup: SERVICES.filter((s) => s.category === 'Makeup'),
  Waxing: SERVICES.filter((s) => s.category === 'Waxing'),
};
