/**
 * Services data matching fonsibycristal.com
 * Order matches the website exactly
 */

import { Service } from '@types/index';

export const SERVICES: Service[] = [
  // Hair Services (order matches website)
  {
    id: 'hair-1',
    name: 'Cuts',
    category: 'Hair',
    description: 'Professional hair cutting service',
    priceMin: 55,
    priceMax: 85,
    duration: 45,
  },
  {
    id: 'hair-2',
    name: 'Fringe Trim',
    category: 'Hair',
    description: 'Quick fringe/bangs trim',
    priceMin: 10,
    priceMax: 15,
    duration: 15,
  },
  {
    id: 'hair-3',
    name: 'Shampoo & Blowouts',
    category: 'Hair',
    description: 'Shampoo, condition, and style blowout',
    priceMin: 45,
    priceMax: 85,
    duration: 60,
  },
  {
    id: 'hair-4',
    name: 'Styling',
    category: 'Hair',
    description: 'Professional hair styling service',
    priceMin: 35,
    priceMax: 120,
    duration: 60,
  },
  {
    id: 'hair-5',
    name: 'Special Occasion Updo',
    category: 'Hair',
    description: 'Elegant updo styling for special events',
    priceMin: 55,
    priceMax: 125,
    duration: 90,
  },
  {
    id: 'hair-6',
    name: 'Men Cuts',
    category: 'Hair',
    description: 'Professional men\'s haircut',
    priceMin: 29.95,
    priceMax: 55,
    duration: 30,
  },
  {
    id: 'hair-7',
    name: 'Perm',
    category: 'Hair',
    description: 'Permanent wave treatment',
    priceMin: 135,
    priceMax: 225,
    duration: 180,
  },
  {
    id: 'hair-8',
    name: 'Keratin Treatment',
    category: 'Hair',
    description: 'Keratin smoothing treatment (consultation required)',
    priceMin: 150,
    priceMax: 250,
    duration: 180,
  },
  {
    id: 'hair-9',
    name: 'Color Retouch',
    category: 'Hair',
    description: 'Root touch-up and color refresh',
    priceMin: 85,
    priceMax: 135,
    duration: 90,
  },
  {
    id: 'hair-10',
    name: 'Full Color',
    category: 'Hair',
    description: 'Complete hair coloring service',
    priceMin: 95,
    priceMax: 205,
    duration: 120,
  },
  {
    id: 'hair-11',
    name: 'Color Correction',
    category: 'Hair',
    description: 'Color correction service (in-person consultation)',
    priceMin: 150,
    priceMax: 400,
    duration: 180,
  },
  {
    id: 'hair-12',
    name: 'Foil Highlights',
    category: 'Hair',
    description: 'Foil highlights and dimensional coloring',
    priceMin: 205,
    priceMax: 350,
    duration: 150,
  },
  {
    id: 'hair-13',
    name: 'Ombre/Balayage',
    category: 'Hair',
    description: 'Ombre or balayage hair coloring (in-person consultation)',
    priceMin: 225,
    priceMax: 400,
    duration: 150,
  },
  {
    id: 'hair-14',
    name: 'Additional Colors',
    category: 'Hair',
    description: 'Additional color services',
    priceMin: 35,
    priceMax: 95,
    duration: 30,
  },
  {
    id: 'hair-15',
    name: 'Partial Foil',
    category: 'Hair',
    description: 'Partial foil highlights',
    priceMin: 75,
    priceMax: 205,
    duration: 120,
  },
  {
    id: 'hair-16',
    name: 'Toners',
    category: 'Hair',
    description: 'Hair toning service',
    priceMin: 35,
    priceMax: 65,
    duration: 45,
  },
  {
    id: 'hair-17',
    name: 'Hair Treatments',
    category: 'Hair',
    description: 'Various hair treatment services',
    priceMin: 35,
    priceMax: 195,
    duration: 60,
  },
  {
    id: 'hair-18',
    name: 'Olaplex Treatment',
    category: 'Hair',
    description: 'Olaplex hair treatment for damage repair',
    priceMin: 125,
    priceMax: 200,
    duration: 90,
  },

  // Bridal Services
  {
    id: 'bridal-1',
    name: 'Bride Package',
    category: 'Bridal',
    description: 'Complete bridal hair and makeup package',
    priceMin: 350,
    priceMax: 350,
    duration: 180,
  },
  {
    id: 'bridal-2',
    name: 'Day of Wedding Party',
    category: 'Bridal',
    description: 'Wedding party styling and makeup (upon request)',
    priceMin: 200,
    priceMax: 500,
    duration: 120,
  },
  {
    id: 'bridal-3',
    name: 'On Site Service',
    category: 'Bridal',
    description: 'On-site bridal services (upon request)',
    priceMin: 250,
    priceMax: 600,
    duration: 180,
  },

  // Makeup Services
  {
    id: 'makeup-1',
    name: 'MAC Full Face',
    category: 'Makeup',
    description: 'Full face makeup application',
    priceMin: 85,
    priceMax: 85,
    duration: 60,
  },
  {
    id: 'makeup-2',
    name: 'MAC Eye Only',
    category: 'Makeup',
    description: 'Eye makeup application only',
    priceMin: 50,
    priceMax: 50,
    duration: 30,
  },
  {
    id: 'makeup-3',
    name: 'On-Site Makeup',
    category: 'Makeup',
    description: 'On-site makeup services (consultation required)',
    priceMin: 150,
    priceMax: 400,
    duration: 90,
  },

  // Waxing Services
  {
    id: 'waxing-1',
    name: 'Eyebrow Waxing',
    category: 'Waxing',
    description: 'Professional eyebrow waxing',
    priceMin: 17,
    priceMax: 35,
    duration: 15,
  },
];

// Group services by category
export const SERVICES_BY_CATEGORY = {
  Hair: SERVICES.filter((s) => s.category === 'Hair'),
  Bridal: SERVICES.filter((s) => s.category === 'Bridal'),
  Makeup: SERVICES.filter((s) => s.category === 'Makeup'),
  Waxing: SERVICES.filter((s) => s.category === 'Waxing'),
};
