/**
 * Services data matching fonsibycristal.com
 * Order matches the website exactly
 */

import { Service } from '@types/index';

export const SERVICES: Service[] = [
  // Hair Services (order matches website)
  {
    id: 'hair-1',
    name: 'Hair Cuts For Women',
    category: 'Hair',
    description: 'Professional women\'s haircut and styling',
    priceMin: 55,
    priceMax: 85,
    duration: 45,
  },
  {
    id: 'hair-2',
    name: 'Fringe Trim',
    category: 'Hair',
    description: 'Bang and fringe trimming',
    priceMin: 10,
    priceMax: 15,
    duration: 15,
  },
  {
    id: 'hair-3',
    name: 'Shampoo & Blowouts',
    category: 'Hair',
    description: 'Professional shampoo and blow dry styling',
    priceMin: 45,
    priceMax: 85,
    duration: 45,
  },
  {
    id: 'hair-4',
    name: 'Styling',
    category: 'Hair',
    description: 'Professional hair styling',
    priceMin: 35,
    priceMax: 120,
    duration: 45,
  },
  {
    id: 'hair-5',
    name: 'Special Occasion Updo',
    category: 'Hair',
    description: 'Updo hairstyle for special occasions',
    priceMin: 55,
    priceMax: 125,
    duration: 60,
  },
  {
    id: 'hair-6',
    name: 'Men Cuts',
    category: 'Hair',
    description: 'Professional men\'s haircut',
    priceMin: 30,
    priceMax: 55,
    duration: 30,
  },
  {
    id: 'hair-7',
    name: 'Perm and Body Wave',
    category: 'Hair',
    description: 'Perm or body wave treatment',
    priceMin: 135,
    priceMax: 225,
    duration: 120,
  },
  {
    id: 'hair-8',
    name: 'Keratin Treatment',
    category: 'Hair',
    description: 'Keratin smoothing treatment - consultation required',
    priceMin: 0,
    priceMax: 0,
    duration: 120,
  },
  {
    id: 'hair-9',
    name: 'Color Retouch',
    category: 'Hair',
    description: 'Root touch up color service',
    priceMin: 85,
    priceMax: 135,
    duration: 75,
  },
  {
    id: 'hair-10',
    name: 'Full Color',
    category: 'Hair',
    description: 'Full head color service',
    priceMin: 95,
    priceMax: 205,
    duration: 120,
  },
  {
    id: 'hair-11',
    name: 'Color Correction',
    category: 'Hair',
    description: 'Color correction service - consultation required',
    priceMin: 0,
    priceMax: 0,
    duration: 180,
  },
  {
    id: 'hair-12',
    name: 'Foil Highlights',
    category: 'Hair',
    description: 'Full foil highlights',
    priceMin: 205,
    priceMax: 205,
    duration: 150,
  },
  {
    id: 'hair-13',
    name: 'Ombre, Balayage, Color Melting',
    category: 'Hair',
    description: 'Ombre, balayage, or color melting technique - consultation required',
    priceMin: 0,
    priceMax: 0,
    duration: 150,
  },
  {
    id: 'hair-14',
    name: 'Additional Colors',
    category: 'Hair',
    description: 'Additional color application',
    priceMin: 35,
    priceMax: 95,
    duration: 30,
  },
  {
    id: 'hair-15',
    name: 'Partial Foil',
    category: 'Hair',
    description: 'Partial foil highlights',
    priceMin: 75,
    priceMax: 205,
    duration: 120,
  },
  {
    id: 'hair-16',
    name: 'Toners',
    category: 'Hair',
    description: 'Toner application for color adjustment',
    priceMin: 35,
    priceMax: 65,
    duration: 30,
  },
  {
    id: 'hair-17',
    name: 'Treatments',
    category: 'Hair',
    description: 'Deep conditioning and repair treatments',
    priceMin: 35,
    priceMax: 195,
    duration: 60,
  },
  {
    id: 'hair-18',
    name: 'Olaplex Bond Shaper',
    category: 'Hair',
    description: 'Olaplex bond shaper curl rebuilding treatment',
    priceMin: 125,
    priceMax: 200,
    duration: 90,
  },

  // Bridal Services
  {
    id: 'bridal-1',
    name: 'The Bride Package',
    category: 'Bridal',
    description: 'Complete bridal hair and makeup package',
    priceMin: 350,
    priceMax: 350,
    duration: 120,
  },
  {
    id: 'bridal-2',
    name: 'Day of Wedding Party',
    category: 'Bridal',
    description: 'Day-of wedding party hair and makeup - upon request',
    priceMin: 0,
    priceMax: 0,
    duration: 90,
  },
  {
    id: 'bridal-3',
    name: 'On Site',
    category: 'Bridal',
    description: 'On-site bridal services - upon request',
    priceMin: 0,
    priceMax: 0,
    duration: 120,
  },

  // Makeup Services
  {
    id: 'makeup-1',
    name: 'MAC Full Face Application',
    category: 'Makeup',
    description: 'Full face MAC makeup application',
    priceMin: 85,
    priceMax: 85,
    duration: 60,
  },
  {
    id: 'makeup-2',
    name: 'MAC Eye Makeup Only',
    category: 'Makeup',
    description: 'Eye makeup application using MAC products',
    priceMin: 50,
    priceMax: 50,
    duration: 30,
  },
  {
    id: 'makeup-3',
    name: 'On-Site Application',
    category: 'Makeup',
    description: 'On-site makeup application - consultation required',
    priceMin: 0,
    priceMax: 0,
    duration: 60,
  },

  // Waxing Services
  {
    id: 'waxing-1',
    name: 'Eyebrow Waxing',
    category: 'Waxing',
    description: 'Professional eyebrow waxing and shaping',
    priceMin: 17,
    priceMax: 35,
    duration: 15,
  },
];

// Group services by category
export const SERVICES_BY_CATEGORY = {
  Hair: SERVICES.filter((s) => s.category === 'Hair'),
  Bridal: SERVICES.filter((s) => s.category === 'Bridal'),
  Makeup: SERVICES.filter((s) => s.category === 'Makeup'),
  Waxing: SERVICES.filter((s) => s.category === 'Waxing'),
};
